import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { Noto_Sans_KR } from "next/font/google";
import QueryProviders from "@/components/provider";
import BottomNavigationBar from "@/components/BottomNavigationBar";

const notoSansKR = Noto_Sans_KR({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  preload: false,
});

export const metadata: Metadata = {
  title: "CashUp Trade Viewer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={notoSansKR.className} suppressHydrationWarning={true}>
        <QueryProviders>{children}</QueryProviders>
        <nav>
          <BottomNavigationBar />
        </nav>
      </body>
    </html>
  );
}
